# Autogenerated wrapper script for libczi_julia_jll for x86_64-w64-mingw32
export libczi_julia

JLLWrappers.@generate_wrapper_header("libczi_julia")
JLLWrappers.@declare_library_product(libczi_julia, "libczi_julia.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libczi_julia,
        "bin\\libczi_julia.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
