# Autogenerated wrapper script for libczi_julia_jll for x86_64-linux-musl-julia_version+1.8.2
export libczi_julia

using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("libczi_julia")
JLLWrappers.@declare_library_product(libczi_julia, "libczi_julia.so")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libczi_julia,
        "lib/libczi_julia.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
